### ISSUE TITLE
One time execution in module after its registration

### ISSUE THREAD

**Issue by ghost** [olegmisar/haxilium#6]
I would like to execute some part of code to initialize the module as soon it got registered/mounted. Is there any event or solution for this?

**Comment by olehmisar** [comment]
No, it is not possible yet. I will make such thing as hooks in module definition.

**Comment by ghost** [comment]
I'm currently working on networking and I need to access haxilium methods inside a module but no callback would be helpful to me. So when do you plan to release the module hooks?

**Comment by olehmisar** [comment]
Now modules have `registered` field — function which will be called when module is registered
